modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"
[[mods]]
modId = "playernametweaks"
version = "${file.jarVersion}"
displayName = "PlayerNameTweaks"
displayURL="https://github.com/TomatoPuddin/PlayerNameTweaks"
authors="TomatoPuddin"
description = '''
'''

[[dependencies.playernametweaks]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playernametweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"

[[dependencies.playernametweaks]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.10.6,)"
ordering = "NONE"
side = "BOTH"
